### ISSUE TITLE
Rewrite diagnosands subsystem

### ISSUE THREAD

**Issue by nfultz** [DeclareDesign/DeclareDesign#148]
Tracking ticket for rewriting diagnosands

  - [x] #146 Nullability ?  
  - [x] #147 NAability ?
  - [x] #141 follow on - Bookkeeping when sims is misspecifiled
  - [x] #116 #117 sorting order of display
  - [x] #144 aggregating estimators with different column-space
