### ISSUE TITLE
checklist for push to CRAN

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#253]
I'd like to push to CRAN on Monday, subject to further review of the package more broadly by @nfultz 

Here's what I know needs to happen before pushing:

- [x] confirm designs in DesignLibrary work @clabima @medinali @jaspercooper 
- [x] confirm everything in blog posts work @macartan @jaspercooper 
- [x] confirm everything in paper works (GB)
- [x] confirm this doesn't cause problems with current CRAN versions of sub-packages
- [ ] coverage -> 100%

Please review!

**Comment by macartan** [comment]
First set of last issues from me:

## Reshape:

* Keep parameters together. hard case:

```
designs1 = expand_design(simple_two_arm_designer, rho = c(.3, .4), prefix = "rho_design")
designs2 = expand_design(simple_two_arm_designer, N = 6:7, ate = 1:2, prefix = "mo_design")
designs3 <- c(designs1, designs2)
kable(simulate_design(designs3, sims = 2), digits = 2)
````

* do not repeat parameter names on est and  se rows
* lets please cut the statistic columns; it is less verbose but still it takes up valuable real estate with little information
* Would be nice if this gave the n steps in the warning: "Error: The sims argument you provided for the designs named design_1, design_2 are not correct. Sims should be of length the number of steps in a design or one."

* Odd repetition of var columns when select is used with add_columns:

Compare:
```
> diagnosis

Research design diagnosis. Diagnosand estimates with bootstrapped standard errors (100 replicates).

 Design Label Estimand Label Estimator Label Coefficient Significance Filter N Sims ate   N Statistic   Bias   RMSE  Power Coverage
     design_1            ATE    my_estimator           Z               FALSE     14 0.4  20  Estimate  -0.03   0.35   0.00     1.00
                                                                                    0.4  20        SE (0.10) (0.05) (0.00)   (0.00)
     design_1            ATE    my_estimator           Z                TRUE      6 0.4  20  Estimate   0.31   0.84   1.00     0.67
                                                                                    0.4  20        SE (0.40) (0.17) (0.00)   (0.21)
     design_2            ATE    my_estimator           Z               FALSE      5 0.4 200  Estimate  -0.19   0.21   0.00     0.80
                                                                                    0.4 200        SE (0.04) (0.05) (0.00)   (0.17)
     design_2            ATE    my_estimator           Z                TRUE     15 0.4 200  Estimate   0.01   0.09   1.00     1.00
                                                                                    0.4 200        SE (0.02) (0.02) (0.00)   (0.00)
```
with:

```
> kable(DeclareDesign::reshape_diagnosis(diagnosis, 
+                         select = c("Significance Filter", "Bias")), 
+       row.names = FALSE)


|Design Label |Estimand Label |Estimator Label |Coefficient |Significance Filter |N Sims |Significance Filter.1 |Bias   |
|:------------|:--------------|:---------------|:-----------|:-------------------|:------|:---------------------|:------|
|design_1     |ATE            |my_estimator    |Z           |FALSE               |14     |FALSE                 |-0.03  |
|             |               |                |            |                    |       |                      |(0.10) |
```

Note that (a) Significance column doubled (b) 

* Select should cover also the leading columns (design id etc
# Error on declare_step ?

```
two_arm <- simple_two_arm_designer(N = 100) + declare_step(X = rnorm(100))
two_arm
Error in ...f(data, ...) : argument "...f" is missing, with no default 
```


# Repeated label issues

```
A <- B <- declare_estimator(Y~Z, model = lm_robust, estimand = "ATE")
repeated_label1 <- simple_two_arm_design + declare_estimator(Y~Z, model = lm_robust, estimand = "ATE") 
repeated_label2 <- simple_two_arm_design + A
repeated_label3 <- simple_two_arm_design + A + B
```

repeated_label1 works and relabels the second estimator label (to call, so not too elegant); repeated_label2 and repeated_label3 do not

Better behavior would be to give a numbered relabelling in teh first and second cases (my_estimator_2) and keep going in the third case (my_estimator_3)

**Comment by macartan** [comment]
On issue 2: Realize declare_step now requires `handler = fabricate`; needs updating in a bunch of posts

**Comment by graemeblair** [comment]
Thanks for these examples; will fix

**Comment by graemeblair** [comment]
please note: the push to CRAN is imminent. no version 1 issues remain. if you have more, please issue them!

**Comment by acoppock** [comment]
I believe all these issues have been addressed.
